feat: Added card view for Room Type
HF5-PROJECT/app pull request #13
Opened 2023-02-28 11:44 UTC by Anders164a

## Description

- Added card view for room type

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-02-28 12:55 UTC, frederikpyt commented on lib/room/type/view/hotel_room_types.dart
> +                HeaderWidget(
![image](https://user-images.githubusercontent.com/54995208/221859925-993c28c3-dfc3-4a07-9074-140f6dcd3505.png)

2023-02-28 13:11 UTC, Anders164a commented on lib/room/type/view/hotel_room_types.dart
> +                HeaderWidget(
Changes added

2023-02-28 13:18 UTC, frederikpyt requested changes

2023-02-28 13:18 UTC, frederikpyt commented on lib/app/widgets/header_back.dart
> +import 'package:flutter/material.dart';
Wrong way of doing this

2023-02-28 13:18 UTC, frederikpyt commented on lib/app/widgets/header_back.dart
> +import 'package:flutter/material.dart';
Add a calculation in the real header

2023-02-28 13:33 UTC, Anders164a commented on lib/app/widgets/header_back.dart
> +import 'package:flutter/material.dart';
Changes added

2023-03-01 07:14 UTC, frederikpyt approved these changes

2023-03-01 07:14 UTC, merged